IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CONTACTOS]') AND type in (N'U'))
	DROP TABLE [dbo].[CONTACTOS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CONTACTOS](
	[CONTACTOSID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](500) NOT NULL default '',
	[MORADA1] [varchar](500) NOT NULL default '',
	[MORADA2] [varchar](500) NOT NULL default '',
	[COD_POSTAL] [varchar](500) NOT NULL default '',
	[LOCALIDADE] [varchar](500) NOT NULL default '',
	[ctrldata] [datetime] NOT NULL default getdate(),
	[ctrlcodop] [varchar](500) NOT NULL default 'AL',
	[ctrldataupdt] [datetime] NULL,
	[ctrlcodopupdt] [varchar](500) NULL,
 CONSTRAINT [PK_CONTACTOS] PRIMARY KEY CLUSTERED 
(
	[CONTACTOSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TIPOS_ESPECIALIDADES]') AND type in (N'U'))
	DROP TABLE [dbo].[TIPOS_ESPECIALIDADES]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TIPOS_ESPECIALIDADES](
	[TIPOS_ESPECIALIDADESID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](500) NOT NULL default '',
	[NOME_EN] [varchar](500) NOT NULL default '',
	[NOME_FR] [varchar](500) NOT NULL default '',
	[NOME_ES] [varchar](500) NOT NULL default '',
	[ordem] [int] NOT NULL default 0,
	[ctrldata] [datetime] NOT NULL default getdate(),
	[ctrlcodop] [varchar](500) NOT NULL default 'AL',
	[ctrldataupdt] [datetime] NULL,
	[ctrlcodopupdt] [varchar](500) NULL,
 CONSTRAINT [PK_TIPOS_ESPECIALIDADES] PRIMARY KEY CLUSTERED 
(
	[TIPOS_ESPECIALIDADESID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_TIPOS_ESPECIALIDADES_NOME] UNIQUE NONCLUSTERED 
(
	[NOME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ESPECIALIDADES]') AND type in (N'U'))
	DROP TABLE [dbo].[ESPECIALIDADES]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ESPECIALIDADES](
	[ESPECIALIDADESID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](500) NOT NULL default '',
	[NOME_EN] [varchar](500) NOT NULL default '',
	[NOME_FR] [varchar](500) NOT NULL default '',
	[NOME_ES] [varchar](500) NOT NULL default '',
	[ID_TIPO] [int] NOT NULL references tipos_especialidades(tipos_especialidadesid),
	[ordem] [int] NOT NULL default 0,
	[ctrldata] [datetime] NOT NULL default getdate(),
	[ctrlcodop] [varchar](500) NOT NULL default 'AL',
	[ctrldataupdt] [datetime] NULL,
	[ctrlcodopupdt] [varchar](500) NULL,
 CONSTRAINT [PK_ESPECIALIDADES] PRIMARY KEY CLUSTERED 
(
	[ESPECIALIDADESID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_ESPECIALIDADES_NOME_TIPO] UNIQUE NONCLUSTERED 
(
	[NOME] ASC,
	[ID_TIPO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PORTFOLIO_TIPO]') AND type in (N'U'))
	DROP TABLE [dbo].[PORTFOLIO_TIPO]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PORTFOLIO_TIPO](
	[PORTFOLIO_TIPOID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](500) NOT NULL default '',
	[NOME_EN] [varchar](500) NOT NULL default '',
	[NOME_FR] [varchar](500) NOT NULL default '',
	[NOME_ES] [varchar](500) NOT NULL default '',
	[ctrldata] [datetime] NOT NULL default getdate(),
	[ctrlcodop] [varchar](500) NOT NULL default 'AL',
	[ctrldataupdt] [datetime] NULL,
	[ctrlcodopupdt] [varchar](500) NULL,
 CONSTRAINT [PK_PORTFOLIO_TIPO] PRIMARY KEY CLUSTERED 
(
	[PORTFOLIO_TIPOID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_PORTFOLIO_TIPO_NOME] UNIQUE NONCLUSTERED 
(
	[NOME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PORTFOLIO]') AND type in (N'U'))
	DROP TABLE [dbo].[PORTFOLIO]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PORTFOLIO](
	[PORTFOLIOID] [int] IDENTITY(1,1) NOT NULL,
	[LOCALIDADE] [varchar](500) NOT NULL default '',
	[TEXTO] [varchar](max) NOT NULL default '',
	[TEXTO_EN] [varchar](max) NOT NULL default '',
	[TEXTO_FR] [varchar](max) NOT NULL default '',
	[TEXTO_ES] [varchar](max) NOT NULL default '',
	[EMPRESA] [varchar](250) NOT NULL default '',
	[ID_TIPO] [int] NOT NULL references portfolio_tipo(portfolio_tipoid),
	[IMAGEM_CAPA] [varchar](500) NOT NULL default '',
	[ORDEM] [int] NOT NULL default 0,
	[ANO] [int] NOT NULL default 2019,
	[ctrldata] [datetime] NOT NULL default getdate(),
	[ctrlcodop] [varchar](500) NOT NULL default 'AL',
	[ctrldataupdt] [datetime] NULL,
	[ctrlcodopupdt] [varchar](500) NULL,
 CONSTRAINT [PK_PORTFOLIO] PRIMARY KEY CLUSTERED 
(
	[PORTFOLIOID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PORTFOLIO_IMAGES]') AND type in (N'U'))
	DROP TABLE [dbo].[PORTFOLIO_IMAGES]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PORTFOLIO_IMAGES](
	[PORTFOLIO_IMAGESID] [int] IDENTITY(1,1) NOT NULL,
	[ID_PORTFOLIO] [int] NOT NULL references portfolio(portfolioid),
	[IMAGEM] [varchar](500) NOT NULL default '',
	[ORDEM] [int] NOT NULL default 0,
	[ctrldata] [datetime] NOT NULL default getdate(),
	[ctrlcodop] [varchar](500) NOT NULL default 'AL',
	[ctrldataupdt] [datetime] NULL,
	[ctrlcodopupdt] [varchar](500) NULL,
 CONSTRAINT [PK_PORTFOLIO_IMAGES] PRIMARY KEY CLUSTERED 
(
	[PORTFOLIO_IMAGESID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_PORTFOLIO_IMAGES_IMAGEM] UNIQUE NONCLUSTERED 
(
	[IMAGEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO






IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TEXTOS]') AND type in (N'U'))
	DROP TABLE [dbo].[TEXTOS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TEXTOS](
	[TEXTOSID] [int] IDENTITY(1,1) NOT NULL,
	[CODIGO] [varchar](100) NOT NULL default '*',
	[NOME] [varchar](500) NOT NULL default '',
	[NOME_EN] [varchar](500) NOT NULL default '',
	[NOME_FR] [varchar](500) NOT NULL default '',
	[NOME_ES] [varchar](500) NOT NULL default '',
	[TEXTO] [varchar](max) NOT NULL default '',
	[TEXTO_EN] [varchar](max) NOT NULL default '',
	[TEXTO_FR] [varchar](max) NOT NULL default '',
	[TEXTO_ES] [varchar](max) NOT NULL default '',
	[ordem] [int] NOT NULL default 0,
	[ctrldata] [datetime] NOT NULL default getdate(),
	[ctrlcodop] [varchar](500) NOT NULL default 'AL',
	[ctrldataupdt] [datetime] NULL,
	[ctrlcodopupdt] [varchar](500) NULL,
 CONSTRAINT [PK_TEXTOS] PRIMARY KEY CLUSTERED 
(
	[TEXTOSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_TEXTOS_CODIGO] UNIQUE NONCLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
